name: CI

on: [push, pull_request]

jobs:
  Tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Test
      run: |
        npm install -g truffle
        npm install -g ganache-cli
        npm install
        ganache-cli -q -u 0x7F7eF2F9D8B0106cE76F66940EF7fc0a3b23C974 &
        sleep 5
        truffle test --network development

  Tests-Flow:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - name: Setup
      run: go get github.com/onflow/flow-go-sdk
    - name: Setup env
      run: |
        echo "::set-env name=GOPATH::$(dirname $GITHUB_WORKSPACE)"
        echo "::add-path::$(dirname $GITHUB_WORKSPACE)/bin"
    - name: Test
      run: |
        cd flow
        flow project start-emulator &
        sleep 5
        flow project deploy
        flow transactions send -c .\mint.cdc --results
