name: CI

on: [push, pull_request]

jobs:
  Tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Test
      run: |
        npm install -g truffle
        npm install
        truffle test
